# Generated by Django 2.2.4 on 2019-08-18 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishe',
            options={'ordering': ['-id']},
        ),
    ]
