# Generated by Django 2.2.4 on 2019-08-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20190818_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishe',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Help to distinguish the dishes that are enabled from those that are not', verbose_name='is enabled'),
        ),
    ]
