# Generated by Django 2.2.4 on 2019-08-16 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0002_auto_20190816_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date time on which the reservation was created.')),
                ('observations', models.TextField(help_text='Customizations of my dishes', verbose_name='Employees Observations')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Help easily distinguish status of Reservation.', verbose_name='confirmed by seller/Nora')),
                ('menu_dishe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.MenuDishes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
