# Generated by Django 2.2.4 on 2019-08-22 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date time on which the reservation was created.')),
                ('observations', models.TextField(help_text='Customizations of my dishes', verbose_name='Employees Observations')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Help easily distinguish status of Reservation.', verbose_name='confirmed by seller/Nora')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date time on which the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', null=True)),
                ('menu_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.MenuDishes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
