# Generated by Django 2.2.4 on 2019-08-16 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.TextField(default="today's menu", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MenuDishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dishes.Dishe')),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menus.Menu')),
            ],
        ),
    ]
