# Generated by Django 2.2.4 on 2019-08-22 01:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date the menu will be available.')),
                ('name', models.TextField(default="today's menu", help_text='Descriptive name.', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date time on which the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='MenuDishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.Dish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Menu')),
            ],
            options={
                'unique_together': {('menu', 'dish')},
            },
        ),
    ]
